### ISSUE TITLE
"pip install onnx-neural-compressor" failed

### ISSUE THREAD

**Issue by ice-tong** [onnx/neural-compressor#26]
I'm glad to see this project and can't wait to try it out, but pip install fails. Is there an official release yet?

![image](https://github.com/onnx/neural-compressor/assets/32220263/a4a092a8-db4c-49c6-a2ef-6a5ac885c0a6)

**Comment by thuang6** [comment]
The first official release was planned in late July,  before the first binary release, please try to install with source.  Thanks
